
import Loom.Test.Velvet.Bench.ContainsConsecutiveNumbers
import Loom.Test.Velvet.Bench.CountSumDivisibleBy
import Loom.Test.Velvet.Bench.CubeElements
import Loom.Test.Velvet.Bench.CubeSurfaceArea
import Loom.Test.Velvet.Bench.DifferenceMinMax
import Loom.Test.Velvet.Bench.ElementWiseModulo
import Loom.Test.Velvet.Bench.FindEvenNumbers
import Loom.Test.Velvet.Bench.FindMajorityElement
import Loom.Test.Velvet.Bench.FindSmallest
import Loom.Test.Velvet.Bench.HasOppositeSign
import Loom.Test.Velvet.Bench.IfPowerOfFour
import Loom.Test.Velvet.Bench.IsDivisibleBy11
import Loom.Test.Velvet.Bench.IsEven
import Loom.Test.Velvet.Bench.IsGreater
import Loom.Test.Velvet.Bench.IsNonPrime
import Loom.Test.Velvet.Bench.IsPrime
import Loom.Test.Velvet.Bench.IsSorted
import Loom.Test.Velvet.Bench.IsSublist
import Loom.Test.Velvet.Bench.KthElement
import Loom.Test.Velvet.Bench.LastDigit
import Loom.Test.Velvet.Bench.MergeSorted
import Loom.Test.Velvet.Bench.MinOfThree
import Loom.Test.Velvet.Bench.Multiply
import Loom.Test.Velvet.Bench.MyMin
import Loom.Test.Velvet.Bench.RemoveElement
import Loom.Test.Velvet.Bench.SumAndAverage
import Loom.Test.Velvet.Bench.SumOfSquaresOfFirstNOddNumbers
import Loom.Test.Velvet.Bench.SwapFirstAndLast
