-- Disabled: contained sorry unrelated to Velvet/Bench.
/-
Extracted expensive grind goals from the 3 outlier benchmarks.
MProd fields decomposed, names prettified.
Each section is standalone with the relevant definitions and grind attributes.
-/
/-
import Lean

open Lean Meta Elab Tactic

@[grind .]
theorem Array.getElem!_push [Inhabited α] (i : Nat) (val : α) (arr : Array α) :
  i <= arr.size → (arr.push val)[i]! = if i < arr.size then arr[i]! else val := by
  intro; grind [Array.extract_succ_right]

-- attribute [-grind] getElem?_neg getElem?_pos getElem!_neg getElem!_pos Array.set!_eq_setIfInBounds
attribute [-grind] getElem?_neg getElem?_pos getElem!_neg getElem!_pos
-- attribute [-grind] Array.setIfInBounds_def Array.set!_eq_setIfInBounds

#check Array.getElem?_set

@[simp, grind .] theorem size_set! {xs : Array α} {i : Nat} {v : α} :
    (xs.set! i v).size = xs.size :=
  sorry

@[grind .] theorem getElem!_set! [Inhabited α] {xs : Array α} {i : Nat} (h : i < xs.size) {v : α} {j : Nat} :
    j < xs.size →
    i < xs.size →
    (xs.set! i v)[j]! = if i ≠ j then xs[j]! else if i = j then v else default:= by
  split <;> simp_all

-- @[grind .] theorem set!_set!_neq [Inhabited α] {xs : Array α} {i j : Nat} {v : α} (h : i ≠ j) :
--     j < xs.size →
--     (xs.set! i v).set! j v = xs.set! j v := by
--   sorry


#check Array.size_set

set_option diagnostics true

example (arr₀ : Array Nat)
  (arr : Array Nat) (n : Nat)
  (h_outer_sorted : ∀ (i j : Nat), i < j ∧ j ≤ n - 1 → arr[i]! ≤ arr[j]!)
  (h_outer_bounds : 1 ≤ n ∧ n ≤ arr.size)
  (h_outer_size : arr.size = arr₀.size)
  (h_outer_not_done : n ≠ arr.size)
  (arr' : Array Nat) (mind : Nat)
  (mind_n : mind <= n)
  (mind_0 : mind ≠ 0)
  (h_inner_sorted : ∀ (i j : Nat), i < j → j ≤ n → mind ≠ j → arr'[i]! ≤ arr'[j]!)
  (h_inner_size : arr'.size = arr₀.size)
  (h_out_of_order : arr'[mind]! < arr'[mind - 1]!) :
  i < j → j ≤ n → j ≠ mind - 1 →
    ((arr'.set! (mind - 1) arr'[mind]!).set! mind arr'[mind - 1]!)[i]! ≤
      ((arr'.set! (mind - 1) arr'[mind]!).set! mind arr'[mind - 1]!)[j]! := by
  intros
  (repeat' rw [getElem!_set!]) <;> try grind
  split <;> try grind
  split <;> try grind
  split <;> try grind
  split <;> try grind
  subst_vars;
  -- apply h_inner_sorted <;> grind
  -- grind --[-getElem?_neg, -getElem?_pos]


set_option diagnostics true

-- NB: Inside mvcgen', grind runs in a persistent GrindM context where
-- the congruence closure state accumulates across all VCs. This means
-- later goals benefit from lemma instances found while solving earlier ones.
-- Standalone grind starts fresh, so some goals that succeed inside mvcgen' fail
-- standalone — even with the same norm.maxSteps. The practical workaround is to
-- decompose MProd state variables before calling grind.

/-! ## DifferenceMinMax — 1 expensive goal (~580ms)

This is the loop-exit VC: the loop counter `i` has reached `a.size`,
and we must produce witnesses for the existential in the postcondition.
grind struggles with the double-∃ + conjunction structure. -/

section DifferenceMinMax

set_option trace.profiler true in
/-- As generated by mvcgen' (MProd not decomposed). `grind` fails standalone —
    inside mvcgen' it succeeds because grind's GrindM state is shared across VCs.
    Decomposing the MProd makes it tractable standalone (~600ms). -/
example (a : Array Int)
    (hpre₁ : ¬a.size = 0)
    (s : MProd Nat (MProd Int Int))
    (hloop : ¬s.fst < a.size)
    (hmx : (∃ j, j < s.fst ∧ a[j]! = s.snd.snd) ∧ ∀ (j : Nat), j < s.fst → a[j]! ≤ s.snd.snd)
    (hmn : (∃ j, j < s.fst ∧ a[j]! = s.snd.fst) ∧ ∀ (j : Nat), j < s.fst → s.snd.fst ≤ a[j]!)
    (hbnd : 1 ≤ s.fst ∧ s.fst ≤ a.size) :
    ∃ mn mx,
      ((∃ i, i < a.size ∧ a[i]! = mn) ∧ ∀ (i : Nat), i < a.size → mn ≤ a[i]!) ∧
      ((∃ i, i < a.size ∧ a[i]! = mx) ∧ ∀ (i : Nat), i < a.size → a[i]! ≤ mx) ∧
      s.snd.snd - s.snd.fst = mx - mn := by
  obtain ⟨i, mn, mx⟩ := s
  grind

set_option trace.profiler true in
/-- DifferenceMinMax loop-exit goal. grind takes ~580ms. -/
example (a : Array Int) (i : Nat) (mn mx : Int)
    (hpre₁ : a.size ≠ 0)
    (hloop : ¬i < a.size)
    (hmx : (∃ j, j < i ∧ a[j]! = mx) ∧ ∀ (j : Nat), j < i → a[j]! ≤ mx)
    (hmn : (∃ j, j < i ∧ a[j]! = mn) ∧ ∀ (j : Nat), j < i → mn ≤ a[j]!)
    (hbnd : 1 ≤ i ∧ i ≤ a.size) :
    ∃ mn' mx',
      ((∃ k, k < a.size ∧ a[k]! = mn') ∧ ∀ (k : Nat), k < a.size → mn' ≤ a[k]!) ∧
      ((∃ k, k < a.size ∧ a[k]! = mx') ∧ ∀ (k : Nat), k < a.size → a[k]! ≤ mx') ∧
      mx - mn = mx' - mn' := by
  grind

end DifferenceMinMax

/-! ## FindEvenNumbers — 3 expensive goals (~1.3s, ~3.6s, ~8.4s)

All three are loop-body preservation VCs for the `isEvenInt x = true` branch.
grind has to reason about `Array.push` and array indexing. -/

section FindEvenNumbers

@[local grind]
def isEvenInt (x : Int) : Bool :=
  x % 2 = 0

set_option trace.profiler true in
/-- FindEvenNumbers goal 1: strictness of indices after push (~1.3s). -/
example (arr : Array Int) (i : Nat) (indices : Array Nat) (result : Array Int)
    (hord : ∀ (k j : Nat), k < j → j < indices.size → indices[k]! < indices[j]!)
    (hval : ∀ (k : Nat), k < indices.size → result[k]! = arr[indices[k]!]!)
    (hbound : ∀ (k : Nat), k < indices.size → indices[k]! < arr.size)
    (hlt : ∀ (k : Nat), k < indices.size → indices[k]! < i)
    (hsz : indices.size = result.size)
    (hcount : ∀ (x : Int), isEvenInt x = true → result.count x = (arr.take i).count x)
    (hcount0 : ∀ (x : Int), isEvenInt x = false → result.count x = 0)
    (hmem : ∀ (x : Int), x ∈ result → isEvenInt x = true)
    (hle : i ≤ arr.size)
    (hi : i < arr.size)
    (heven : isEvenInt arr[i]! = true) :
    ∀ (k j : Nat), k < j → j < (indices.push i).size →
      (indices.push i)[k]! < (indices.push i)[j]! := by
  grind

set_option trace.profiler true in
/-- FindEvenNumbers goal 2: value preservation after push (~3.6s). -/
example (arr : Array Int) (i : Nat) (indices : Array Nat) (result : Array Int)
    (hord : ∀ (k j : Nat), k < j → j < indices.size → indices[k]! < indices[j]!)
    (hval : ∀ (k : Nat), k < indices.size → result[k]! = arr[indices[k]!]!)
    (hbound : ∀ (k : Nat), k < indices.size → indices[k]! < arr.size)
    (hlt : ∀ (k : Nat), k < indices.size → indices[k]! < i)
    (hsz : indices.size = result.size)
    (hcount : ∀ (x : Int), isEvenInt x = true → result.count x = (arr.take i).count x)
    (hcount0 : ∀ (x : Int), isEvenInt x = false → result.count x = 0)
    (hmem : ∀ (x : Int), x ∈ result → isEvenInt x = true)
    (hle : i ≤ arr.size)
    (hi : i < arr.size)
    (heven : isEvenInt arr[i]! = true) :
    ∀ (k : Nat), k < (indices.push i).size →
      (result.push arr[i]!)[k]! = arr[(indices.push i)[k]!]! := by
  grind

-- set_option trace.profiler true
set_option diagnostics true



-- set_option maxHeartbeats 10000000 in
/-- FindEvenNumbers goal 3: index bound preservation after push (~8.4s). -/
example (arr : Array Int) (i : Nat) (indices : Array Nat) (result : Array Int)
    (hord : ∀ (k j : Nat), k < j → j < indices.size → indices[k]! < indices[j]!)
    (hval : ∀ (k : Nat), k < indices.size → result[k]! = arr[indices[k]!]!)
    (hbound : ∀ (k : Nat), k < indices.size → indices[k]! < arr.size)
    (hlt : ∀ (k : Nat), k < indices.size → indices[k]! < i)
    (hsz : indices.size = result.size)
    (hcount : ∀ (x : Int), isEvenInt x = true → result.count x = (arr.take i).count x)
    (hcount0 : ∀ (x : Int), isEvenInt x = false → result.count x = 0)
    (hmem : ∀ (x : Int), x ∈ result → isEvenInt x = true)
    (hle : i ≤ arr.size)
    (hi : i < arr.size)
    (heven : isEvenInt arr[i]! = true) :
    ∀ (k : Nat), k < (indices.push i).size →
      (indices.push i)[k]! < arr.size := by
  grind

end FindEvenNumbers

/-! ## MergeSorted — vc22: last-element bound after push from a1 (~1s, grind fails)

This is the loop-body VC for the `a2` exhausted branch (taking from `a1`).
After pushing `a1[i]`, we must show the last element of the result
is ≤ `a1[i+1]`. Requires reasoning about `isSorted` and
`Array.push`/`getElem!` on the last element.
grind fails on this goal (~1s). -/

section MergeSorted'

@[local grind]
def isSortedNat (arr : Array Nat) : Prop :=
  ∀ (i j : Nat), i < j → j < arr.size → arr[i]! ≤ arr[j]!

theorem isSortedNat_le (arr : Array Nat) (i : Nat) :
  isSortedNat arr → i + 1 < arr.size → arr[i]! ≤ arr[i + 1]! := by
  intro s; apply s; grind

set_option trace.profiler true in
/-- MergeSorted vc22 with MProd (as generated by mvcgen'). grind fails (~1s). -/
example (a1 a2 : Array Nat)
    (hsort1 : isSortedNat a1)
    (hsort2 : isSortedNat a2)
    (s : MProd Nat (MProd Nat (Array Nat)))
    (hlast2 : 0 < s.snd.snd.size → s.snd.fst < a2.size → s.snd.snd[s.snd.snd.size - 1]! ≤ a2[s.snd.fst]!)
    (hlast1 : 0 < s.snd.snd.size → s.fst < a1.size → s.snd.snd[s.snd.snd.size - 1]! ≤ a1[s.fst]!)
    (hcnt : ∀ v, s.snd.snd.count v = (a1.take s.fst).count v + (a2.take s.snd.fst).count v)
    (hsort : isSortedNat s.snd.snd)
    (hrsz : s.snd.snd.size = s.fst + s.snd.fst)
    (hj : s.snd.fst ≤ a2.size)
    (hi : s.fst ≤ a1.size)
    (hcond : s.fst < a1.size ∨ s.snd.fst < a2.size)
    (ha2done : a2.size ≤ s.snd.fst) :
    0 < (s.snd.snd.push a1[s.fst]!).size →
      s.fst + 1 < a1.size →
        (s.snd.snd.push a1[s.fst]!)[(s.snd.snd.push a1[s.fst]!).size - 1]! ≤ a1[s.fst + 1]! := by
  -- obtain ⟨i, j, result⟩ := s
  try first | grind | sorry

end MergeSorted'
-/
